services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/dream-league
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network
    # Add these security options for Puppeteer/Chromium
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
